php-study:
  build:
    context: .
    dockerfile: ./php-fpm/study/Dockerfile
  container_name: php-study
  working_dir: /var/www/study
  volumes:
    - .../study:/var/www/study
    - .../app-logs/php-study:/var/www/study/storage/logs
  networks:
    - dev-net
  ports:
    - "9001:9001"

nginx:
  image: nginx:stable-alpine
  container_name: local-nginx
  ports:
    - "80:80"
  volumes:
    - .../study:/var/www/study
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/logs:/var/log/nginx
  depends_on:
    - php-study
  networks:
    - dev-net