services:
  mysql-80:
    image: mysql:8.0
    container_name: local-mysql-80
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data/80:/var/lib/mysql
    networks:
      - dev-net
    restart: unless-stopped
  redis:
    image: redis:7.2-alpine
    container_name: local-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - dev-net
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    container_name: local-nginx
    ports:
      - "80:80"
    volumes:
      - ../study:/var/www/study
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php-study
    networks:
      - dev-net
  jenkins:
    image: jenkins/jenkins:lts
    container_name: local-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_data:/var/jenkins_home
      - ../study:/var/www/study
    networks:
      - dev-net
    restart: unless-stopped

  #Project
  php-study:
    build:
      context: .
      dockerfile: ./php-fpm/study/Dockerfile
    container_name: php-study
    working_dir: /var/www/study
    volumes:
      - ../study:/var/www/study
    depends_on:
      - mysql-80
      - redis
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge
    name: dev-net