php-crm1:
  build:
    context: .
    dockerfile: ./php-fpm/crm1/Dockerfile
  container_name: php-crm1
  working_dir: /var/www/crm1
  volumes:
    - .../educa_crm:/var/www/crm1
  networks:
    - dev-net